#!/bin/bash
# Script para atualizar código na VPS e verificar cookies

echo "📥 Atualizando código na VPS..."
echo ""
echo "Execute na VPS:"
echo ""
echo "cd ~/content-orchestrator"
echo "git fetch origin"
echo "git reset --hard origin/main"
echo "git pull origin main"
echo ""
echo "🔍 Verificando cookies dentro do container:"
echo ""
echo "docker exec content-orchestrator ls -la /app/data/cookies.txt"
echo "docker exec content-orchestrator head -5 /app/data/cookies.txt"
echo "docker exec content-orchestrator grep -c '^\.youtube\.com' /app/data/cookies.txt"
echo ""
echo "🔧 Ajustando permissões (se necessário):"
echo ""
echo "chown 1000:1000 ~/content-orchestrator/data/cookies.txt"
echo "chmod 644 ~/content-orchestrator/data/cookies.txt"
echo ""
echo "🔨 Rebuild e restart:"
echo ""
echo "docker compose build content-orchestrator --no-cache"
echo "docker compose up -d content-orchestrator"
echo ""
echo "📊 Verificar logs:"
echo ""
echo "docker logs -f content-orchestrator"
